[
  {
    id: 'cs_test_a1K3USVpGamQoarbjmDuadJVY4r84uJHgQF5nadVjubmsY5Vz5JLZXWyC1',
    object: 'checkout.session',
    after_expiration: null,
    allow_promotion_codes: null,
    amount_subtotal: 2000,
    amount_total: 2000,
    automatic_tax: { enabled: false, liability: null, status: null },
    billing_address_collection: null,
    cancel_url: 'http://localhost:4000/cancel',
    client_reference_id: null,
    client_secret: null,
    consent: null,
    consent_collection: null,
    created: 1725022609,
    currency: 'usd',
    currency_conversion: null,
    custom_fields: [],
    custom_text: {
      after_submit: null,
      shipping_address: null,
      submit: null,
      terms_of_service_acceptance: null,
    },
    customer: 'cus_Ql0ODAdsg2joyV',
    customer_creation: 'always',
    customer_details: {
      address: {
        city: 'sssss',
        country: 'IN',
        line1: 'sss',
        line2: 'ss',
        postal_code: '233333',
        state: 'KA',
      },
      email: 'superadmin@pipex.com',
      name: 'ssssss',
      phone: '+919999999999',
      tax_exempt: 'none',
      tax_ids: [],
    },
    customer_email: null,
    expires_at: 1725109009,
    invoice: 'in_1PtUNnP9iQtlLJGOi16S8zGn',
    invoice_creation: null,
    livemode: false,
    locale: null,
    metadata: {},
    mode: 'subscription',
    payment_intent: null,
    payment_link: null,
    payment_method_collection: 'always',
    payment_method_configuration_details: null,
    payment_method_options: { card: { request_three_d_secure: 'automatic' } },
    payment_method_types: ['card', 'amazon_pay', 'link'],
    payment_status: 'paid',
    phone_number_collection: { enabled: true },
    recovered_from: null,
    saved_payment_method_options: {
      allow_redisplay_filters: ['always'],
      payment_method_remove: null,
      payment_method_save: null,
    },
    setup_intent: null,
    shipping_address_collection: { allowed_countries: ['IN', 'US', 'AE'] },
    shipping_cost: null,
    shipping_details: {
      address: {
        city: 'sssss',
        country: 'IN',
        line1: 'sss',
        line2: 'ss',
        postal_code: '233333',
        state: 'KA',
      },
      name: 'ssssss',
    },
    shipping_options: [],
    status: 'complete',
    submit_type: null,
    subscription: 'sub_1PtUNnP9iQtlLJGOnhJfA0gD',
    success_url:
      'http://localhost:4000/success?session_id={CHECKOUT_SESSION_ID}',
    total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
    ui_mode: 'hosted',
    url: null,
  },
  {
    object: 'list',
    data: [
      {
        id: 'li_1PtUNhP9iQtlLJGOpVIH5uAp',
        object: 'item',
        amount_discount: 0,
        amount_subtotal: 2000,
        amount_tax: 0,
        amount_total: 2000,
        currency: 'usd',
        description: 'starter',
        price: {
          id: 'price_1PtN22P9iQtlLJGOGSRkaMvk',
          object: 'price',
          active: true,
          billing_scheme: 'per_unit',
          created: 1724994358,
          currency: 'usd',
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: 'prod_QksnVUAdpY3NIB',
          recurring: {
            aggregate_usage: null,
            interval: 'month',
            interval_count: 1,
            meter: null,
            trial_period_days: null,
            usage_type: 'licensed',
          },
          tax_behavior: 'unspecified',
          tiers_mode: null,
          transform_quantity: null,
          type: 'recurring',
          unit_amount: 2000,
          unit_amount_decimal: '2000',
        },
        quantity: 1,
      },
    ],
    has_more: false,
    url: '/v1/checkout/sessions/cs_test_a1K3USVpGamQoarbjmDuadJVY4r84uJHgQF5nadVjubmsY5Vz5JLZXWyC1/line_items',
  },
];
